<?php
/**
 * Amadeco QuickView Module
 *
 * @category   Amadeco
 * @package    Amadeco_QuickView
 * @author     Ilan Parmentier
 */

/**
 * ResultPage (isIsolated => true) = $layoutContent
 * $block & $escaper are not available
 *
 * @var string $layoutContent
 */
?>
<link rel="stylesheet" type="text/css" href="<?= /* noEscape */ $this->getViewFileUrl('mage/gallery/gallery.css') ?>">
<?= /* @noEscape */ $layoutContent ?>